import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Box, Container, Paper, Typography, CircularProgress, Chip, Divider, Grid } from '@mui/material';
import { CheckCircle, ErrorOutline } from '@mui/icons-material';
import axios from 'axios';

export const VerifyLabResult = () => {
  const { id } = useParams<{ id: string }>();
  const [loading, setLoading] = useState(true);
  const [order, setOrder] = useState<any>(null);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchOrder = async () => {
      try {
        const res = await axios.get(`/api/lims/verify/${id}`);
        setOrder(res.data);
      } catch (err) {
        setError('Could not verify this laboratory result. It may be invalid or not yet completed.');
      } finally {
        setLoading(false);
      }
    };
    if (id) fetchOrder();
  }, [id]);

  if (loading) {
    return (
      <Box display="flex" flexDirection="column" alignItems="center" justifyContent="center" minHeight="100vh" bgcolor="#f5f5f5">
        <CircularProgress size={60} thickness={4} />
        <Typography mt={3} variant="h6" color="text.secondary">Verifying Result Authenticity...</Typography>
      </Box>
    );
  }

  if (error || !order) {
    return (
      <Box display="flex" flexDirection="column" alignItems="center" justifyContent="center" minHeight="100vh" bgcolor="#fff0f0">
        <ErrorOutline color="error" sx={{ fontSize: 80, mb: 2 }} />
        <Typography variant="h5" color="error" fontWeight="bold">Verification Failed</Typography>
        <Typography mt={1} color="text.secondary" textAlign="center" maxWidth={400}>{error}</Typography>
      </Box>
    );
  }

  return (
    <Container maxWidth="md" sx={{ py: 6 }}>
      <Paper elevation={4} sx={{ borderRadius: 4, overflow: 'hidden' }}>
        <Box bgcolor="success.main" color="white" py={3} px={4} display="flex" alignItems="center" gap={2}>
          <CheckCircle sx={{ fontSize: 40 }} />
          <Box>
            <Typography variant="h5" fontWeight="bold">Verified Authentic Result</Typography>
            <Typography variant="body2" sx={{ opacity: 0.9 }}>This record is authentic and was generated by Faith Foundation Mission Hospital, Nsukka</Typography>
          </Box>
        </Box>
        
        <Box p={4}>
          <Grid container spacing={3}>
            <Grid item xs={12} md={6}>
              <Typography variant="subtitle2" color="text.secondary" textTransform="uppercase">Patient Details</Typography>
              <Typography variant="h6" fontWeight="bold" mt={1}>
                {order.patient?.lastName}, {order.patient?.firstName}
              </Typography>
              <Typography variant="body2" mt={0.5}>
                Lab No: {order.orderNumber}
              </Typography>
              <Typography variant="body2" mt={0.5}>
                Age: {order.patient?.birthDate ? new Date().getFullYear() - new Date(order.patient.birthDate).getFullYear() : 'N/A'} yrs
              </Typography>
            </Grid>
            <Grid item xs={12} md={6}>
              <Typography variant="subtitle2" color="text.secondary" textTransform="uppercase">Order Details</Typography>
              <Typography variant="body2" mt={1}>
                <strong>Status:</strong> <Chip label={order.status} size="small" color={order.status === 'COMPLETED' ? 'success' : 'warning'} />
              </Typography>
              <Typography variant="body2" mt={1}>
                <strong>Requested On:</strong> {new Date(order.createdAt).toLocaleString()}
              </Typography>
            </Grid>
          </Grid>

          <Divider sx={{ my: 4 }} />

          <Typography variant="h6" fontWeight="bold" mb={3}>Confirmed Test Results</Typography>
          
          {order.items?.map((item: any) => (
            <Box key={item.id} mb={3} p={2} bgcolor="#f8f9fa" borderRadius={2} border="1px solid #e9ecef">
              <Grid container spacing={2}>
                <Grid item xs={12} sm={6}>
                  <Typography variant="subtitle2" color="text.secondary">Test Name</Typography>
                  <Typography variant="body1" fontWeight="bold">{item.test?.testName}</Typography>
                </Grid>
                <Grid item xs={12} sm={6}>
                  <Typography variant="subtitle2" color="text.secondary">Result Value</Typography>
                  <Typography variant="body1" fontWeight="bold" color="primary.main">
                    {item.result?.resultValue || 'Pending'} {item.result?.resultValue ? item.result?.resultUnit : ''}
                  </Typography>
                </Grid>
              </Grid>
            </Box>
          ))}
          
        </Box>
      </Paper>
    </Container>
  );
};
